##use localhost if you want to run app outside docker compose
rabbitmqURI: "amqp://guest:guest@rabbitmq:5672/"
mongodbURI: "mongodb://appuser:appsecret@mongodb:27017/hospital"
mongodbDatabase: "hospital"
mongodbCollection: "config"
queueName: "mosaiq"
