# docker-compose.yml
services:

  andeshl7sender:
    container_name: hl7sender
    build: .
    restart: always

    ports:
      - "8888:8888"
    volumes:
      - ./config.yaml:/app/config.yaml
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
